//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace index.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubItem
    {
        public long sub_id { get; set; }
        public Nullable<long> item_id { get; set; }
        public string sub_item_name { get; set; }
        public string description { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
